# Generated by Django 5.2.5 on 2025-12-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
